In [1]:
# import numpy
import numpy as np

## Numpy Data Types and Attributes

In [2]:
# NumPy's main datatype is ndarray (n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# checking the sata type
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,3.7,6.4]])
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# shape attribute
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
# ndim attribute (shows the number of dimensions)
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# dtype attribute
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
# size attribute
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
# type function
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  3.7  6.4