In [1]:
# import numpy
import numpy as np

## Numpy Data Types and Attributes

In [2]:
# NumPy's main datatype is ndarray (n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# checking the sata type
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,3.7,6.4]])
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# shape attribute
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
# ndim attribute (shows the number of dimensions)
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# dtype attribute
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
# size attribute
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
# type function
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  3.7  6.4

## Creating Numpy Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[8, 0, 9, 7, 9],
       [8, 4, 3, 7, 6],
       [1, 5, 9, 3, 0]])

In [26]:
random_array2= np.random.random((5,3))
random_array2

array([[0.6140612 , 0.11116877, 0.46159459],
       [0.88306421, 0.44430497, 0.09496918],
       [0.2296203 , 0.2420805 , 0.22802731],
       [0.26471328, 0.51267257, 0.38140562],
       [0.62538898, 0.92611235, 0.30850492]])

In [27]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.30585956, 0.99691866, 0.73292017],
       [0.19647179, 0.97728644, 0.76510032],
       [0.79621881, 0.12674507, 0.06962183],
       [0.18515669, 0.15261968, 0.79825323],
       [0.86804092, 0.3398303 , 0.73207344]])

In [30]:
# Pseudo random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])