In [1]:
# import numpy
import numpy as np

## Numpy Data Types and Attributes

In [2]:
# NumPy's main datatype is ndarray (n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# checking the sata type
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,3.7,6.4]])
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# shape attribute
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
# ndim attribute (shows the number of dimensions)
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# dtype attribute
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
# size attribute
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
# type function
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  3.7  6.4

## Creating Numpy Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[8, 0, 9, 7, 9],
       [8, 4, 3, 7, 6],
       [1, 5, 9, 3, 0]])

In [26]:
random_array2= np.random.random((5,3))
random_array2

array([[0.6140612 , 0.11116877, 0.46159459],
       [0.88306421, 0.44430497, 0.09496918],
       [0.2296203 , 0.2420805 , 0.22802731],
       [0.26471328, 0.51267257, 0.38140562],
       [0.62538898, 0.92611235, 0.30850492]])

In [27]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.30585956, 0.99691866, 0.73292017],
       [0.19647179, 0.97728644, 0.76510032],
       [0.79621881, 0.12674507, 0.06962183],
       [0.18515669, 0.15261968, 0.79825323],
       [0.86804092, 0.3398303 , 0.73207344]])

In [30]:
# Pseudo random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing Arrays and Matrices

In [31]:
# Finding Unique elements of an array
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1

array([1, 2, 3])

In [34]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
# viewing elements by index
a1[0]

1

In [37]:
a2[0]

array([1. , 2. , 3.3])

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Slicing in arrays
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [42]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [45]:
# get the first four numbers of the innermost array
a4[:, :, :, :2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

## Manipulating and comparing NumPy Arrays

### Arithmetic

In [47]:
a1

array([1, 2, 3])

In [48]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# add two arrays
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [50]:
# subtraction
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [51]:
# Multiplication
a1*ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
# Broadcasting in NumPy
# How to reshape NumPy Array

a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [55]:
# Division
a1/ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [56]:
# Floor Division (removes the decimals bu rounding down)
a2//a1

array([[1., 1., 1.],
       [4., 1., 2.]])

In [57]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [58]:
# exponent
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 13.69, 40.96]])

In [60]:
# The square function
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 13.69, 40.96]])

In [61]:
# The add function
np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [62]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [63]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1.7, 0.4]])

In [65]:
np.mod(a2,2)

array([[1. , 0. , 1.3],
       [0. , 1.7, 0.4]])

In [69]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [70]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Performing the same operation on a number of things

In [71]:
a1

array([1, 2, 3])

In [72]:
sum(a1)

6

In [73]:
np.sum(a1)

6

Use Python's methods `sum()` on python datatypes and use NumPy's methods of NumPy arrays `np.sum()`

In [74]:
# Creating a massive NumPy array
massive_array = np.random.random(100000)
massive_array

array([0.16494046, 0.36980809, 0.14644176, ..., 0.55947553, 0.62297663,
       0.05077999])

In [76]:
massive_array.size

100000

In [78]:
massive_array[:100]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839,
       0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093,
       0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628,
       0.31321833, 0.96541622, 0.58846509, 0.65966841, 0.53320625,
       0.23053302, 0.39486929, 0.61880856, 0.47486752, 0.47013219,
       0.71607453, 0.287991  , 0.38346223, 0.74916984, 0.87845219,
       0.10286336, 0.09237389, 0.35404666, 0.55181626, 0.03362509,
       0.96896177, 0.32099724, 0.22126269, 0.1412639 , 0.09725993,
       0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909,
       0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938,
       0.50831545, 0.16684751, 0.77905102, 0.8649333 , 0.41139672,
       0.13997259, 0.03322239, 0.98257496, 0.37329075, 0.42007537,
       0.05058812, 0.36549611, 0.01662797, 0.23074234, 0.7649117 ,
       0.94412352, 0.74999925, 0.33940382, 0.48954894, 0.33898

In [79]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [81]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's sum()

24.9 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
168 µs ± 9.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [82]:
a2

array([[1. , 2. , 3.3],
       [4. , 3.7, 6.4]])

In [83]:
np.mean(a2)

3.4

In [84]:
np.max(a2)

6.4

In [85]:
np.min(a2)

1.0

In [86]:
np.std(a2)

1.6921386861996075

In [87]:
np.var(a2)

2.8633333333333337

## Standard deviation and variance

In [88]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [89]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [90]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [91]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt