In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [11]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [12]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [13]:
# Attributes of the 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
# Create an array of shape (10,2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# create an array of shape(7,2,3) with only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float = np.random.random((3,5))
random_float

array([[0.20260255, 0.52502897, 0.49377364, 0.46013353, 0.70870345],
       [0.38475365, 0.23134721, 0.32157536, 0.78273572, 0.42903486],
       [0.309211  , 0.71505684, 0.98298524, 0.43807844, 0.4491821 ]])

In [28]:
# Set the random seed to 42
np.random.seed(seed = 42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [32]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_2 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array_2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Find the 0'th index of the latest array you created
random_array_2[0]

array([7, 8, 3, 1, 4, 2, 8])

In [39]:
# Get the first 2 rows of latest array you created
random_array_2[:2,:]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_2[:2,:2]

array([[7, 8],
       [4, 2]])

In [41]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_3 = np.random.randint(10, size = (3,5))
array_ones = np.ones((3,5))

In [42]:
random_array_3

array([[1, 4, 7, 9, 8],
       [8, 0, 8, 6, 8],
       [7, 0, 7, 7, 2]])

In [43]:
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Add the two arrays
random_array_3 + array_ones

array([[ 2.,  5.,  8., 10.,  9.],
       [ 9.,  1.,  9.,  7.,  9.],
       [ 8.,  1.,  8.,  8.,  3.]])

In [47]:
# Create another array of shape(5,3)
array_ones_2 = np.ones((5,3))
array_ones_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# Try add the array of ones and the other most recent array together
array_ones_2 + array_ones

# The error occurs due to different shapes of the two arrays.
# We can solve this by changing the shape of one of the arrays to match the other.

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [50]:
# Create another array od ones with shape (3,5) (-> already done)
# Subtract the new array of ones from the other most recent array
random_array_3 - array_ones

array([[ 0.,  3.,  6.,  8.,  7.],
       [ 7., -1.,  7.,  5.,  7.],
       [ 6., -1.,  6.,  6.,  1.]])

In [51]:
# Multiply the ones array with the latest array
random_array_3 * array_ones

array([[1., 4., 7., 9., 8.],
       [8., 0., 8., 6., 8.],
       [7., 0., 7., 7., 2.]])

In [52]:
# Take the latest array to the power of 2 using '**'
random_array_3 ** 2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [53]:
# Do the same thing with np.square()
np.square(random_array_3)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [54]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_3)

5.466666666666667

In [55]:
# Find the maximum of the latest array using np.max()
np.max(random_array_3)

9

In [56]:
# Find the minimum of the latest array using np.min()
np.min(random_array_3)

0

In [57]:
# Find the standard deviation of the latest array
np.std(random_array_3)

3.0739045022396008

In [58]:
# Find the variance of the latest array
np.var(random_array_3)

9.448888888888888

In [60]:
# Reshape the latest array to (3,5,1)
random_array_3.reshape((3,5,1))

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [61]:
# Transpose the latest array
random_array_3.T

# the transpose changes the shape of the data in such a way that the 
# rows become columns and the columns become rows

array([[1, 8, 7],
       [4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2]])

In [62]:
random_array_3

array([[1, 4, 7, 9, 8],
       [8, 0, 8, 6, 8],
       [7, 0, 7, 7, 2]])

In [63]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ra1 = np.random.randint(10, size=(3,3))
ra2 = np.random.randint(10, size=(3,2))

In [64]:
ra1

array([[0, 7, 2],
       [2, 0, 4],
       [9, 6, 9]])

In [65]:
ra2

array([[8, 6],
       [8, 7],
       [1, 0]])

In [66]:
# Perform a dot product on the newest arrays you created
np.dot(ra1,ra2)

array([[ 58,  49],
       [ 20,  12],
       [129,  96]])

In [67]:
ra1.shape, ra2.shape, np.dot(ra1,ra2).shape

((3, 3), (3, 2), (3, 2))

In [69]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ra3 = np.random.randint(10, size = (4,3))
ra4 = np.random.randint(20, size = (4,3))

In [70]:
ra3

array([[0, 4, 9],
       [6, 6, 8],
       [9, 9, 2],
       [6, 0, 3]])

In [71]:
ra4

array([[ 3,  4,  6],
       [12, 14, 10],
       [ 3, 12,  6],
       [18,  1,  9]])

In [72]:
# Perform a dot product on the two newest arrays you created
ra3.dot(ra4)

# Error occurs because the two arrays are not compatible to calculate dot product

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [73]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(ra3, ra4.T)

array([[ 70, 146, 102,  85],
       [ 90, 236, 138, 186],
       [ 75, 254, 147, 189],
       [ 36, 102,  36, 135]])

In [74]:
# Compare the two arrays with '>'
ra3 > ra4

array([[False, False,  True],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [75]:
ra3

array([[0, 4, 9],
       [6, 6, 8],
       [9, 9, 2],
       [6, 0, 3]])

In [76]:
ra4

array([[ 3,  4,  6],
       [12, 14, 10],
       [ 3, 12,  6],
       [18,  1,  9]])

In [77]:
# Compare the two arrays with '>='
ra3 >= ra4

array([[False,  True,  True],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [78]:
# Find which elements of the first array are greater than 7
ra3 > 7

array([[False, False,  True],
       [False, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [79]:
# Which parts of each array are equal? (try using '==')
ra3 == ra4

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [81]:
# Sort one of the arrays you just created in ascending order
np.sort(ra3)

array([[0, 4, 9],
       [6, 6, 8],
       [2, 9, 9],
       [0, 3, 6]])